### ISSUE TITLE
data doesn't seem to persist to the the flat-file database when using memory adapter.

### ISSUE THREAD

**Issue by Marak** [creationix/node-persistence#7]
data will get written to the flat-file (with a bit of a delay?), but when i restart node, the db is empty.

:-(

**Comment by creationix** [comment]
There seems to be some sort of race condition with the current implementation.  It's on my todo list to make it more reliable.  I'll look at it real quick and see if it's something easy.

**Comment by Marak** [comment]
duplicate of issue #1
